# Generated by Django 5.2 on 2025-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_result_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_threshold', models.IntegerField(default=20, verbose_name='آستانه پایین')),
                ('medium_threshold', models.IntegerField(default=40, verbose_name='آستانه متوسط')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات آستانه\u200cهای ADHD',
                'verbose_name_plural': 'تنظیمات آستانه\u200cهای ADHD',
            },
        ),
    ]
